apiVersion: apps/v1
kind: Deployment
metadata:
  name: post
  labels:
    app: reddit
    component: comment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reddit
      component: comment
  template:
    metadata:
      name: post
      labels:
        app: reddit
        component: comment
    spec:
      containers:
      - image: 870414/post
        name: post
        env:
          - name: POST_DATABASE_HOST
            value: post-db
