kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: o/lyYzzWA5cHYKQJTidBwB/QPa56cTSTGsZMIvyhf6g=
      - identity: {}
